# Usar la última imagen de Ubuntu
FROM ubuntu:latest

# Actualizar la lista de paquetes
RUN apt-get update

#Instalar actualizaciones
RUN apt-get upgrade -y

# Comando por defecto que se ejecuta al iniciar el contenedor
CMD ["echo", "Hello, World!"]